Add optional IP selection handler
ipinfo/laravel pull request #39
Opened 2022-07-07 17:35 UTC by SobanMahmood

Closes #8.

2022-07-14 10:13 UTC, UmanShahzad requested changes

2022-07-18 01:37 UTC, SobanMahmood commented
@UmanShahzad thank you for the review, the mentioned changes have been made.

2022-07-18 03:53 UTC, UmanShahzad approved these changes

2022-07-18 03:53 UTC, merged

2022-07-19 08:35 UTC, UmanShahzad commented
Released in v2.4.0.